version: "3.8"

services:
  genoss:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4321:4321
    volumes:
      - ./:/app

  hf_local:
    image: ghcr.io/huggingface/text-generation-inference:0.9
    command: --model-id gpt2
    # Share model folders to not redownload
    volumes:
      - ./local_models:/data
    shm_size: 1g
    # Apple silicon is sad
    platform: linux/x86_64
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [ gpu ]
