version: "3.8"

services:
  genoss:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4321:4321
    volumes:
      - ./:/app
    environment:
      - UVICORN_RELOAD=${UVICORN_RELOAD:-0}
      - UVICORN_LOG_LEVEL=${UVICORN_LOG_LEVEL:-info}
